//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lib.DAL.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventPlanSummary
    {
        public int ID { get; set; }
        public int EventTypeID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string EventTypeDisplayName { get; set; }
        public int TotalRSVP { get; set; }
        public int TotalRSVPEstimate { get; set; }
        public string EventList { get; set; }
    }
}
